# Generated by Django 4.1 on 2024-07-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_available_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationColor',
        ),
        migrations.DeleteModel(
            name='VariationSize',
        ),
    ]
