# Generated by Django 4.1 on 2024-07-30 16:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_variant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
